
spring:
  profiles: default

server:
  port: 8080

mysql:
  url:
  username: root
  password: ax3kuN4guthe

---


spring:
  profiles: prod

server:
  port: 8081

mysql:
  url: ${APP_URL}
  username: ${APP_USERNAME}
  password: ${APP_PASSWORD}