hello: "C'est le mode dev"

spring:
  profiles: default

server:
  port: 8080

mysql:
  url: "jdbc:mysql://127.0.0.1:3306/kata_sql_restaurant?serverTimezone=GMT"
  username: root
  password: i-am-root

---
hello: "c'est la prod"

spring:
  profiles: prod

server:
  port: 8081

mysql:
  url: ${APP_URL}
  username: ${APP_USERNAME}
  password: ${APP_PASSWORD}


#---
#
#app :
#  ext(r)ernal api : https://....